In [5]:
!pip install pandas
!pip install scikit-learn
!pip install pickle

Requirement already satisfied: pandas in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting scikit-learn
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/3b/67/be3d369f40d8178ba3bd86635d132e08cb5329b023e4669d9426d84bc007/scikit_learn-1.9.0-cp311-cp311-win_amd64.whl.metadata
  Using cached scikit_learn-1.9.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from scikit-learn) (2.4.6)
Collecting scipy>=1.10.0 (from scikit-learn)
  Obtaining dependency information for scipy>=1.10.0 from https://files.pythonhosted.org/packages/95/da/0d1df507cf574b3f224ccc3d45244c9a1d732c81dcb26b1e8a766ae271a8/scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata
  Using cached scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Obtaining dependency information for joblib>=1.4.0 from https://files.pythonhosted.org/packages/7b/91/984aca2ec129e2757d1e4e3c81c3fcda9d0f85b74670a094cc443d9ee949/joblib-1.5.3-py3-none-any.whl.metadata
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Obtaining dependency information for narwhals>=2.0.1 from https://files.pythonhosted.org/packages/eb/dc/55481808fd70ef1567cf13540ffd4702af3f74b112e35427564b03f79c2d/narwhals-2.25.0-py3-none-any.whl.metadata
  Downloading narwhals-2.25.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Obtaining dependency information for threadpoolctl>=3.5.0 from https://files.pythonhosted.org/packages/32/d5/f9a850d79b0851d1d4ef6456097579a9005b31fea68726a4ae5f2d82ddd9/threadpoolctl-3.6.0-py3-none-any.whl.metadata
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp311-cp311-win_amd64.whl (8.3 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading narwhals-2.25.0-py3-none-any.whl (467 kB)
   ---------------------------------------- 0.0/467.4 kB ? eta -:--:--
   -------- ------------------------------- 102.4/467.4 kB 2.0 MB/s eta 0:00:01
   ------------------------------- -------- 368.6/467.4 kB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 467.4/467.4 kB 3.7 MB/s eta 0:00:00
Using cached scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, scikit-learn
Successfully installed joblib-1.5.3 narwhals-2.25.0 scikit-learn-1.9.0 scipy-1.17.1 threadpoolctl-3.6.0

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [36]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

##### In this we need to predict whether the person will exit the bank or not

In [37]:
### Load the dataset
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [38]:
# Preprocess the data
### Drop irrelevant features(columns)
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1) ## axis=1 means column wise

# We are droping these columns becuase these are not usable means without these also we can predict whether the person will exit the bank or not

data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [39]:
# In this we can take geography and gender can be taken as categorical variable so we need to encode categorical variables

## Encode categorical variables

label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender']) ## we use fit_transform() because fit() -> learn unique categories, transform() -> convert those categories into numbers ex: the encoder first learns the categories : Male, Female then decides numerical mapping : Femal -> 0 and Male -> 
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
### OneHot encode 'Geography' because it has more than 2 different categories

from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']]) ## it expects 2D data so we are given [[]]
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [41]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [ ]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [ ]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [45]:
### Combine one hot encoder columns with the original data
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [ ]:
## Save the encoders and scaler

with open('label_encoder_gender.pkl','wb') as file:   # wb means write byte
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [47]:
## Divide the dataset into Independent and dependent features

X= data.drop('Exited',axis=1)  # Independent
y=data['Exited'] # dependent

# Split the data in training and testing sets

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# Scale these features

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [48]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(8000, 12))

In [49]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

##### We save encoders and scaler so that after deployment, when a new user enters raw data, our application can load those files and transform the new data exactly the same way as the training data before giving it to the ANN model.

# ANN Implementation

In [53]:
%pip install tensorflow

Collecting tensorflow
  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/8f/a2/6d7e6a738e302530586d484895de2cf3fc158ad9c73b4504a670b2956dd9/tensorflow-2.21.0-cp311-cp311-win_amd64.whl.metadata
  Downloading tensorflow-2.21.0-cp311-cp311-win_amd64.whl.metadata (4.5 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/58/0a/a10b45aab35b175aded078a462dc8d0c698f5b13946e7cb0869097b78bb6/absl_py-2.5.0-py3-none-any.whl.metadata
  Downloading absl_py-2.5.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Obtaining dependency information for astunparse>=1.6.0 from https://files.pythonhosted.org/packages/2b/03/13dde6512ad7b4557eb792fbcf0c653af6076b81e5941d36ec61f7ce6028/astunparse-1.6.3-py2.py3-none-any.whl.metadata
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Obtaining dependency information for flatbuffers>=25.9.23 from https://files.pythonhosted.org/packages/e8/2d/d2a548598be01649e2d46231d151a6c56d10b964d94043a335ae56ea2d92/flatbuffers-25.12.19-py2.py3-none-any.whl.metadata
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Obtaining dependency information for gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 from https://files.pythonhosted.org/packages/1d/33/f1c6a276de27b7d7339a34749cc33fa87f077f921969c47185d34a887ae2/gast-0.7.0-py3-none-any.whl.metadata
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Obtaining dependency information for google_pasta>=0.1.1 from https://files.pythonhosted.org/packages/a3/de/c648ef6835192e6e2cc03f40b19eeda4382c49b5bafb43d88b931c4c74ac/google_pasta-0.2.0-py3-none-any.whl.metadata
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Obtaining dependency information for libclang>=13.0.0 from https://files.pythonhosted.org/packages/0b/2d/3f480b1e1d31eb3d6de5e3ef641954e5c67430d5ac93b7fa7e07589576c7/libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Obtaining dependency information for opt_einsum>=2.3.2 from https://files.pythonhosted.org/packages/23/cd/066e86230ae37ed0be70aae89aabf03ca8d9f39c8aea0dec8029455b5540/opt_einsum-3.4.0-py3-none-any.whl.metadata
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from tensorflow) (26.3)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Obtaining dependency information for protobuf<8.0.0,>=6.31.1 from https://files.pythonhosted.org/packages/0e/4e/12cb93270967a2affff5b3f720694700d4d87712a67afd05c8cb3f6fa52c/protobuf-7.36.0-cp310-abi3-win_amd64.whl.metadata
  Downloading protobuf-7.36.0-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting requests<3,>=2.21.0 (from tensorflow)
  Obtaining dependency information for requests<3,>=2.21.0 from https://files.pythonhosted.org/packages/a0/f4/c67b0b3f1b9245e8d266f0f112c500d50e5b4e83cb6f3b71b6528104182a/requests-2.34.2-py3-none-any.whl.metadata
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: setuptools in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from tensorflow) (65.5.0)
Requirement already satisfied: six>=1.12.0 in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Obtaining dependency information for termcolor>=1.1.0 from https://files.pythonhosted.org/packages/33/d1/8bb87d21e9aeb323cc03034f5eaf2c8f69841e40e4853c2627edf8111ed3/termcolor-3.3.0-py3-none-any.whl.metadata
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from tensorflow) (4.16.0)
Collecting wrapt>=1.11.0 (from tensorflow)
  Obtaining dependency information for wrapt>=1.11.0 from https://files.pythonhosted.org/packages/4a/62/ecc969b13b141fef89b888c9760821cb01a86ac8fc953911592c8e1e1522/wrapt-2.3.0-cp311-cp311-win_amd64.whl.metadata
  Using cached wrapt-2.3.0-cp311-cp311-win_amd64.whl.metadata (7.6 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Obtaining dependency information for grpcio<2.0,>=1.24.3 from https://files.pythonhosted.org/packages/df/ed/e0ffeb4c848699c194dc9fb6a29ab29bcb2b6aac8c416bf18c51bfe8242c/grpcio-1.83.0-cp311-cp311-win_amd64.whl.metadata
  Downloading grpcio-1.83.0-cp311-cp311-win_amd64.whl.metadata (3.8 kB)
Collecting keras>=3.12.0 (from tensorflow)
  Obtaining dependency information for keras>=3.12.0 from https://files.pythonhosted.org/packages/8d/b3/c9b848bbdba18e765a8051917c0cc82585b64278ce87895f2e521a27438f/keras-3.15.1-py3-none-any.whl.metadata
  Downloading keras-3.15.1-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from tensorflow) (2.4.6)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Obtaining dependency information for h5py<3.15.0,>=3.11.0 from https://files.pythonhosted.org/packages/db/0c/6c3f879a0f8e891625817637fad902da6e764e36919ed091dc77529004ac/h5py-3.14.0-cp311-cp311-win_amd64.whl.metadata
  Downloading h5py-3.14.0-cp311-cp311-win_amd64.whl.metadata (2.7 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Obtaining dependency information for ml_dtypes<1.0.0,>=0.5.1 from https://files.pythonhosted.org/packages/07/23/8870bb62d6e499d6bcbc1242b9f11689bae00a3d39d3684a9aefad8b6ee6/ml_dtypes-0.6.0-cp311-cp311-win_amd64.whl.metadata
  Downloading ml_dtypes-0.6.0-cp311-cp311-win_amd64.whl.metadata (8.8 kB)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Obtaining dependency information for wheel<1.0,>=0.23.0 from https://files.pythonhosted.org/packages/2e/29/69cfbb602cd91690c55d38ba9fe53e6a7e76a6fa647bf38f19c138d25449/wheel-0.48.0-py3-none-any.whl.metadata
  Downloading wheel-0.48.0-py3-none-any.whl.metadata (2.3 kB)
Collecting rich (from keras>=3.12.0->tensorflow)
  Obtaining dependency information for rich from https://files.pythonhosted.org/packages/82/3b/64d4899d73f91ba49a8c18a8ff3f0ea8f1c1d75481760df8c68ef5235bf5/rich-15.0.0-py3-none-any.whl.metadata
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras>=3.12.0->tensorflow)
  Obtaining dependency information for namex from https://files.pythonhosted.org/packages/b2/bc/465daf1de06409cdd4532082806770ee0d8d7df434da79c76564d0f69741/namex-0.1.0-py3-none-any.whl.metadata
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow)
  Obtaining dependency information for optree from https://files.pythonhosted.org/packages/da/a8/d28c1fe0f0c8a4eb332f73cae896abab6d4ec40605b406c6a91f792034e0/optree-0.20.0-cp311-cp311-win_amd64.whl.metadata
  Downloading optree-0.20.0-cp311-cp311-win_amd64.whl.metadata (33 kB)
Collecting charset_normalizer<4,>=2 (from requests<3,>=2.21.0->tensorflow)
  Obtaining dependency information for charset_normalizer<4,>=2 from https://files.pythonhosted.org/packages/e3/57/32f0ccea59e8612057c61d6fd22ef2cb63cca93c9fe594094919696ac170/charset_normalizer-3.5.1-cp311-cp311-win_amd64.whl.metadata
  Downloading charset_normalizer-3.5.1-cp311-cp311-win_amd64.whl.metadata (46 kB)
     ---------------------------------------- 0.0/46.7 kB ? eta -:--:--
     ---------------------------------------- 46.7/46.7 kB ? eta 0:00:00
Collecting idna<4,>=2.5 (from requests<3,>=2.21.0->tensorflow)
  Obtaining dependency information for idna<4,>=2.5 from https://files.pythonhosted.org/packages/57/b0/0e52c878c53f245edd3a11020f20979b3f490f245af532c7cae3027754b5/idna-3.19-py3-none-any.whl.metadata
  Downloading idna-3.19-py3-none-any.whl.metadata (9.2 kB)
Collecting urllib3<3,>=1.26 (from requests<3,>=2.21.0->tensorflow)
  Obtaining dependency information for urllib3<3,>=1.26 from https://files.pythonhosted.org/packages/7f/3e/5db95bcf282c52709639744ca2a8b149baccf648e39c8cc87553df9eae0c/urllib3-2.7.0-py3-none-any.whl.metadata
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests<3,>=2.21.0->tensorflow)
  Obtaining dependency information for certifi>=2023.5.7 from https://files.pythonhosted.org/packages/0b/a7/71ac2cff56fec219ed242bb11b8efb69fcc4bec75db06fb7bfe35de520e6/certifi-2026.7.22-py3-none-any.whl.metadata
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.12.0->tensorflow)
  Obtaining dependency information for markdown-it-py>=2.2.0 from https://files.pythonhosted.org/packages/b3/81/4da04ced5a082363ecfa159c010d200ecbd959ae410c10c0264a38cac0f5/markdown_it_py-4.2.0-py3-none-any.whl.metadata
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.21.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow)
  Obtaining dependency information for mdurl~=0.1 from https://files.pythonhosted.org/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl.metadata
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading tensorflow-2.21.0-cp311-cp311-win_amd64.whl (350.8 MB)
   ---------------------------------------- 0.0/350.8 MB ? eta -:--:--
   ---------------------------------------- 0.8/350.8 MB 24.1 MB/s eta 0:00:15
   ---------------------------------------- 1.6/350.8 MB 20.5 MB/s eta 0:00:18
   ---------------------------------------- 2.3/350.8 MB 18.6 MB/s eta 0:00:19
   ---------------------------------------- 3.6/350.8 MB 20.6 MB/s eta 0:00:17
   ---------------------------------------- 4.1/350.8 MB 18.6 MB/s eta 0:00:19
    --------------------------------------- 4.8/350.8 MB 18.2 MB/s eta 0:00:20
    --------------------------------------- 5.1/350.8 MB 18.0 MB/s eta 0:00:20
    --------------------------------------- 5.9/350.8 MB 17.1 MB/s eta 0:00:21
    --------------------------------------- 6.6/350.8 MB 16.2 MB/s eta 0:00:22
    --------------------------------------- 7.3/350.8 MB 16.0 MB/s eta 0:00:22
    --------------------------------------- 7.7/350.8 MB 15.5 MB/s eta 0:00:23
    --------------------------------------- 8.2/350.8 MB 15.0 MB/s eta 0:00:23
    --------------------------------------- 8.7/350.8 MB 14.7 MB/s eta 0:00:24
   - -------------------------------------- 9.2/350.8 MB 14.4 MB/s eta 0:00:24
   - -------------------------------------- 9.8/350.8 MB 14.2 MB/s eta 0:00:25
   - -------------------------------------- 10.2/350.8 MB 13.9 MB/s eta 0:00:25
   - -------------------------------------- 10.8/350.8 MB 13.4 MB/s eta 0:00:26
   - -------------------------------------- 11.3/350.8 MB 13.1 MB/s eta 0:00:26
   - -------------------------------------- 11.9/350.8 MB 13.1 MB/s eta 0:00:26
   - -------------------------------------- 12.5/350.8 MB 12.6 MB/s eta 0:00:27
   - -------------------------------------- 13.0/350.8 MB 12.6 MB/s eta 0:00:27
   - -------------------------------------- 13.6/350.8 MB 11.9 MB/s eta 0:00:29
   - -------------------------------------- 14.1/350.8 MB 12.1 MB/s eta 0:00:28
   - -------------------------------------- 14.7/350.8 MB 11.9 MB/s eta 0:00:29
   - -------------------------------------- 15.3/350.8 MB 12.4 MB/s eta 0:00:28
   - -------------------------------------- 16.0/350.8 MB 11.9 MB/s eta 0:00:29
   - -------------------------------------- 16.6/350.8 MB 11.9 MB/s eta 0:00:29
   - -------------------------------------- 17.2/350.8 MB 12.1 MB/s eta 0:00:28
   -- ------------------------------------- 17.9/350.8 MB 12.1 MB/s eta 0:00:28
   -- ------------------------------------- 18.6/350.8 MB 12.4 MB/s eta 0:00:27
   -- ------------------------------------- 19.3/350.8 MB 12.6 MB/s eta 0:00:27
   -- ------------------------------------- 20.0/350.8 MB 12.8 MB/s eta 0:00:26
   -- ------------------------------------- 20.7/350.8 MB 13.4 MB/s eta 0:00:25
   -- ------------------------------------- 21.5/350.8 MB 13.6 MB/s eta 0:00:25
   -- ------------------------------------- 22.2/350.8 MB 13.9 MB/s eta 0:00:24
   -- ------------------------------------- 22.9/350.8 MB 13.9 MB/s eta 0:00:24
   -- ------------------------------------- 23.7/350.8 MB 14.2 MB/s eta 0:00:23
   -- ------------------------------------- 24.2/350.8 MB 14.6 MB/s eta 0:00:23
   -- ------------------------------------- 24.8/350.8 MB 14.2 MB/s eta 0:00:23
   -- ------------------------------------- 25.3/350.8 MB 14.2 MB/s eta 0:00:23
   -- ------------------------------------- 25.9/350.8 MB 14.2 MB/s eta 0:00:23
   --- ------------------------------------ 26.4/350.8 MB 14.2 MB/s eta 0:00:23
   --- ------------------------------------ 26.9/350.8 MB 13.6 MB/s eta 0:00:24
   --- ------------------------------------ 27.4/350.8 MB 13.6 MB/s eta 0:00:24
   --- ------------------------------------ 28.0/350.8 MB 13.4 MB/s eta 0:00:25
   --- ------------------------------------ 28.6/350.8 MB 13.4 MB/s eta 0:00:25
   --- ------------------------------------ 29.2/350.8 MB 13.1 MB/s eta 0:00:25
   --- ------------------------------------ 29.8/350.8 MB 13.1 MB/s eta 0:00:25
   --- ------------------------------------ 30.4/350.8 MB 13.1 MB/s eta 0:00:25
   --- ------------------------------------ 31.0/350.8 MB 12.8 MB/s eta 0:00:25
   --- ------------------------------------ 31.7/350.8 MB 12.8 MB/s eta 0:00:25
   --- ------------------------------------ 32.3/350.8 MB 12.6 MB/s eta 0:00:26
   --- ------------------------------------ 32.9/350.8 MB 12.6 MB/s eta 0:00:26
   --- ------------------------------------ 33.6/350.8 MB 12.6 MB/s eta 0:00:26
   --- ------------------------------------ 34.3/350.8 MB 12.6 MB/s eta 0:00:26
   --- ------------------------------------ 34.8/350.8 MB 12.6 MB/s eta 0:00:26
   ---- ----------------------------------- 35.6/350.8 MB 12.8 MB/s eta 0:00:25
   ---- ----------------------------------- 36.3/350.8 MB 13.1 MB/s eta 0:00:25
   ---- ----------------------------------- 37.0/350.8 MB 13.6 MB/s eta 0:00:24
   ---- ----------------------------------- 37.5/350.8 MB 13.4 MB/s eta 0:00:24
   ---- ----------------------------------- 37.9/350.8 MB 13.1 MB/s eta 0:00:24
   ---- ----------------------------------- 38.3/350.8 MB 13.1 MB/s eta 0:00:24
   ---- ----------------------------------- 38.7/350.8 MB 12.6 MB/s eta 0:00:25
   ---- ----------------------------------- 39.1/350.8 MB 12.6 MB/s eta 0:00:25
   ---- ----------------------------------- 39.6/350.8 MB 12.4 MB/s eta 0:00:26
   ---- ----------------------------------- 40.0/350.8 MB 12.1 MB/s eta 0:00:26
   ---- ----------------------------------- 40.5/350.8 MB 12.1 MB/s eta 0:00:26
   ---- ----------------------------------- 40.9/350.8 MB 11.9 MB/s eta 0:00:27
   ---- ----------------------------------- 41.4/350.8 MB 11.7 MB/s eta 0:00:27
   ---- ----------------------------------- 41.9/350.8 MB 11.5 MB/s eta 0:00:27
   ---- ----------------------------------- 42.4/350.8 MB 11.5 MB/s eta 0:00:27
   ---- ----------------------------------- 42.9/350.8 MB 11.3 MB/s eta 0:00:28
   ---- ----------------------------------- 43.4/350.8 MB 11.1 MB/s eta 0:00:28
   ----- ---------------------------------- 44.0/350.8 MB 11.1 MB/s eta 0:00:28
   ----- ---------------------------------- 44.5/350.8 MB 10.9 MB/s eta 0:00:29
   ----- ---------------------------------- 45.0/350.8 MB 10.9 MB/s eta 0:00:29
   ----- ---------------------------------- 45.6/350.8 MB 10.7 MB/s eta 0:00:29
   ----- ---------------------------------- 46.2/350.8 MB 10.7 MB/s eta 0:00:29
   ----- ---------------------------------- 46.8/350.8 MB 10.6 MB/s eta 0:00:29
   ----- ---------------------------------- 47.4/350.8 MB 10.7 MB/s eta 0:00:29
   ----- ---------------------------------- 47.7/350.8 MB 10.4 MB/s eta 0:00:30
   ----- ---------------------------------- 48.3/350.8 MB 10.7 MB/s eta 0:00:29
   ----- ---------------------------------- 49.0/350.8 MB 10.9 MB/s eta 0:00:28
   ----- ---------------------------------- 49.7/350.8 MB 11.3 MB/s eta 0:00:27
   ----- ---------------------------------- 50.3/350.8 MB 11.5 MB/s eta 0:00:27
   ----- ---------------------------------- 51.0/350.8 MB 11.9 MB/s eta 0:00:26
   ----- ---------------------------------- 51.7/350.8 MB 12.1 MB/s eta 0:00:25
   ----- ---------------------------------- 52.4/350.8 MB 12.4 MB/s eta 0:00:25
   ------ --------------------------------- 53.1/350.8 MB 12.8 MB/s eta 0:00:24
   ------ --------------------------------- 53.8/350.8 MB 13.1 MB/s eta 0:00:23
   ------ --------------------------------- 54.5/350.8 MB 13.4 MB/s eta 0:00:23
   ------ --------------------------------- 55.3/350.8 MB 13.6 MB/s eta 0:00:22
   ------ --------------------------------- 55.9/350.8 MB 13.9 MB/s eta 0:00:22
   ------ --------------------------------- 56.7/350.8 MB 13.9 MB/s eta 0:00:22
   ------ --------------------------------- 57.2/350.8 MB 14.6 MB/s eta 0:00:21
   ------ --------------------------------- 57.9/350.8 MB 14.2 MB/s eta 0:00:21
   ------ --------------------------------- 58.3/350.8 MB 13.9 MB/s eta 0:00:21
   ------ --------------------------------- 58.7/350.8 MB 13.6 MB/s eta 0:00:22
   ------ --------------------------------- 59.1/350.8 MB 13.4 MB/s eta 0:00:22
   ------ --------------------------------- 59.5/350.8 MB 13.1 MB/s eta 0:00:23
   ------ --------------------------------- 60.0/350.8 MB 12.8 MB/s eta 0:00:23
   ------ --------------------------------- 60.5/350.8 MB 12.9 MB/s eta 0:00:23
   ------ --------------------------------- 60.9/350.8 MB 12.6 MB/s eta 0:00:24
   ------ --------------------------------- 61.2/350.8 MB 12.1 MB/s eta 0:00:24
   ------- -------------------------------- 61.9/350.8 MB 12.1 MB/s eta 0:00:24
   ------- -------------------------------- 62.3/350.8 MB 11.9 MB/s eta 0:00:25
   ------- -------------------------------- 62.9/350.8 MB 11.7 MB/s eta 0:00:25
   ------- -------------------------------- 63.4/350.8 MB 11.5 MB/s eta 0:00:26
   ------- -------------------------------- 63.9/350.8 MB 11.3 MB/s eta 0:00:26
   ------- -------------------------------- 64.2/350.8 MB 11.3 MB/s eta 0:00:26
   ------- -------------------------------- 64.8/350.8 MB 10.9 MB/s eta 0:00:27
   ------- -------------------------------- 65.3/350.8 MB 10.7 MB/s eta 0:00:27
   ------- -------------------------------- 65.9/350.8 MB 10.7 MB/s eta 0:00:27
   ------- -------------------------------- 66.4/350.8 MB 10.6 MB/s eta 0:00:27
   ------- -------------------------------- 67.1/350.8 MB 10.4 MB/s eta 0:00:28
   ------- -------------------------------- 67.7/350.8 MB 10.4 MB/s eta 0:00:28
   ------- -------------------------------- 68.3/350.8 MB 10.6 MB/s eta 0:00:27
   ------- -------------------------------- 68.9/350.8 MB 10.9 MB/s eta 0:00:26
   ------- -------------------------------- 69.6/350.8 MB 11.3 MB/s eta 0:00:25
   -------- ------------------------------- 70.3/350.8 MB 11.5 MB/s eta 0:00:25
   -------- ------------------------------- 71.0/350.8 MB 11.7 MB/s eta 0:00:24
   -------- ------------------------------- 71.6/350.8 MB 12.1 MB/s eta 0:00:24
   -------- ------------------------------- 72.0/350.8 MB 11.9 MB/s eta 0:00:24
   -------- ------------------------------- 72.6/350.8 MB 12.1 MB/s eta 0:00:23
   -------- ------------------------------- 73.3/350.8 MB 12.3 MB/s eta 0:00:23

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [77]:
%pip install tensorboard

Collecting tensorboard
  Obtaining dependency information for tensorboard from https://files.pythonhosted.org/packages/37/4b/cd2eec9642781a8f5b2fb9994e3933a7b259ab18e9d49aeede9b5acf6311/tensorboard-2.21.0-py3-none-any.whl.metadata
  Downloading tensorboard-2.21.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: absl-py>=0.4 in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from tensorboard) (2.5.0)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from tensorboard) (1.83.0)
Collecting markdown>=2.6.8 (from tensorboard)
  Obtaining dependency information for markdown>=2.6.8 from https://files.pythonhosted.org/packages/64/69/4a5af2bc115a9a33fefe51709749de8262be3f9ba063d1753a837cdbc49c/markdown-3.10.3-py3-none-any.whl.metadata
  Downloading markdown-3.10.3-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: numpy>=1.12.0 in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from tensorboard) (2.4.6)
Requirement already satisfied: packaging in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from tensorboard) (26.3)
Collecting pillow (from tensorboard)
  Obtaining dependency information for pillow from https://files.pythonhosted.org/packages/63/c6/4bad1b18d132a50b27e1365e1ab163616f7a5bb56d330f66f9d1d9d4f9d4/pillow-12.3.0-cp311-cp311-win_amd64.whl.metadata
  Downloading pillow-12.3.0-cp311-cp311-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from tensorboard) (7.36.0)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from tensorboard) (65.5.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard)
  Obtaining dependency information for tensorboard-data-server<0.8.0,>=0.7.0 from https://files.pythonhosted.org/packages/7a/13/e503968fefabd4c6b2650af21e110aa8466fe21432cd7c43a84577a89438/tensorboard_data_server-0.7.2-py3-none-any.whl.metadata
  Downloading tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard)
  Obtaining dependency information for werkzeug>=1.0.1 from https://files.pythonhosted.org/packages/93/8c/2e650f2afeb7ee576912636c23ddb621c91ac6a98e66dc8d29c3c69446e1/werkzeug-3.1.8-py3-none-any.whl.metadata
  Downloading werkzeug-3.1.8-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\mypc\desktop\generativeai\annclassificationproject\venv\lib\site-packages (from grpcio<2.0,>=1.74.0->tensorboard) (4.16.0)
Collecting markupsafe>=2.1.1 (from werkzeug>=1.0.1->tensorboard)
  Obtaining dependency information for markupsafe>=2.1.1 from https://files.pythonhosted.org/packages/83/8a/4414c03d3f891739326e1783338e48fb49781cc915b2e0ee052aa490d586/markupsafe-3.0.3-cp311-cp311-win_amd64.whl.metadata
  Downloading markupsafe-3.0.3-cp311-cp311-win_amd64.whl.metadata (2.8 kB)
Downloading tensorboard-2.21.0-py3-none-any.whl (5.5 MB)
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   - -------------------------------------- 0.2/5.5 MB 4.1 MB/s eta 0:00:02
   ------- -------------------------------- 1.0/5.5 MB 10.7 MB/s eta 0:00:01
   ----------------- ---------------------- 2.5/5.5 MB 17.4 MB/s eta 0:00:01
   ------------------- -------------------- 2.7/5.5 MB 14.4 MB/s eta 0:00:01
   ----------------------- ---------------- 3.2/5.5 MB 13.7 MB/s eta 0:00:01
   --------------------------- ------------ 3.8/5.5 MB 13.4 MB/s eta 0:00:01
   -------------------------------- ------- 4.4/5.5 MB 13.5 MB/s eta 0:00:01
   ---------------------------------------  5.5/5.5 MB 14.6 MB/s eta 0:00:01
   ---------------------------------------  5.5/5.5 MB 14.6 MB/s eta 0:00:01
   ---------------------------------------  5.5/5.5 MB 14.6 MB/s eta 0:00:01
   ---------------------------------------  5.5/5.5 MB 14.6 MB/s eta 0:00:01
   ---------------------------------------  5.5/5.5 MB 14.6 MB/s eta 0:00:01
   ---------------------------------------  5.5/5.5 MB 14.6 MB/s eta 0:00:01
   ---------------------------------------  5.5/5.5 MB 7.8 MB/s eta 0:00:01
   ---------------------------------------  5.5/5.5 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------- 5.5/5.5 MB 6.9 MB/s eta 0:00:00
Downloading markdown-3.10.3-py3-none-any.whl (110 kB)
   ---------------------------------------- 0.0/110.8 kB ? eta -:--:--
   ---------------------------------------- 110.8/110.8 kB 2.1 MB/s eta 0:00:00
Downloading tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)
Downloading werkzeug-3.1.8-py3-none-any.whl (226 kB)
   ---------------------------------------- 0.0/226.5 kB ? eta -:--:--
   --------------------------------------- 226.5/226.5 kB 14.4 MB/s eta 0:00:00
Downloading pillow-12.3.0-cp311-cp311-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ----------- ---------------------------- 2.1/7.2 MB 33.6 MB/s eta 0:00:01
   ---------------------- ----------------- 4.0/7.2 MB 18.4 MB/s eta 0:00:01
   -------------------------- ------------- 4.7/7.2 MB 15.1 MB/s eta 0:00:01
   ---------------------------------- ----- 6.2/7.2 MB 16.4 MB/s eta 0:00:01
   ---------------------------------------  7.1/7.2 MB 15.6 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 13.2 MB/s eta 0:00:00
Downloading markupsafe-3.0.3-cp311-cp311-win_amd64.whl (15 kB)
Installing collected packages: tensorboard-data-server, pillow, markupsafe, markdown, werkzeug, tensorboard
Successfully installed markdown-3.10.3 markupsafe-3.0.3 pillow-12.3.0 tensorboard-2.21.0 tensorboard-data-server-0.7.2 werkzeug-3.1.8
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [56]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [59]:
(X_train.shape[1],)

(12,)

In [ ]:
## Build Our ANN Model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ## 1st hidden layer connected wit input layer and here 64 means this hidden layer contains 64 neurons and we need to mention only once input_shape and dont need to write for every time
    Dense(32,activation='relu'), ## hidden layer 2
    Dense(1,activation='sigmoid') ## Output layer
]
)

c:\Users\MYPC\Desktop\GenerativeAI\ANNClassificationProject\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [62]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [68]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [ ]:
## To perform Forward and Backward Propagation first we need to compile the model
## Compile the model

model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

# or we can directly use optimizer="adam"

NameError: name 'model' is not defined

In [74]:
## Set up the Tensorboard

from tensorflow.keras.callbacks import EarlyStopping,TensorBoard


log_dir="logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%m%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [ ]:
## Set up Early Stopping
## Suppose we have an 100 epochs(one complete pass through an entire training dataset) so for each epoch if loss is decreasing then ok if loss stops decreasing then we need to stop so we use early stopping

early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True) # patience=5 meanch be patient for 10 epoch if there is no change then stop

In [80]:
### Train the model

history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.8615 - loss: 0.3389 - val_accuracy: 0.8580 - val_loss: 0.3423
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8626 - loss: 0.3358 - val_accuracy: 0.8565 - val_loss: 0.3460
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8634 - loss: 0.3350 - val_accuracy: 0.8475 - val_loss: 0.3700
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8619 - loss: 0.3336 - val_accuracy: 0.8555 - val_loss: 0.3399
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8635 - loss: 0.3298 - val_accuracy: 0.8505 - val_loss: 0.3602
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8648 - loss: 0.3310 - val_accuracy: 0.8560 - val_loss: 0.3507
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8679 - loss: 0.3258 - val_accuracy: 0.8600 - val_loss: 0.3458
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8694 - loss: 0.3229 - val_accuracy: 0.8590 - val_loss: 0.3537
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8690 - loss: 0.3215 - val_accuracy: 0.8555 - val_loss: 0.3541
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8676 - loss: 0.3233 - val_accuracy: 0.8475 - val_loss: 0.3859
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8717 - loss: 0.3171 - val_accuracy: 0.8590 - val_loss: 0.3495
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8687 - loss: 0.3169 - val_accuracy: 0.8610 - val_loss: 0.3499
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8701 - loss: 0.3150 - val_accuracy: 0.8640 - val_loss: 0.3492
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8736 - loss: 0.3094 - val_accuracy: 0.8650 - val_loss: 0.3519

In [81]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [1]:
## Load Tensorboard Extension

%load_ext tensorboard

In [10]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 7000), started 0:13:38 ago. (Use '!kill 7000' to kill it.)